"""Make aida_uri nullable

Revision ID: 7b235e0c0de9
Revises: d4865d22d392
Create Date: 2024-01-16 00:12:24.876265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b235e0c0de9'
down_revision = 'd4865d22d392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column('aida_uri',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('papers_aida_uri_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_unique_constraint('papers_aida_uri_key', ['aida_uri'])
        batch_op.alter_column('aida_uri',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
