"""Add topic table

Revision ID: b28693579b91
Revises: f56431b4f46f
Create Date: 2023-12-16 12:15:01.088841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28693579b91'
down_revision = 'f56431b4f46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cso_uri', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('dbpedia_uri', sa.String(), nullable=True),
    sa.Column('description_pulled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cso_uri')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    # ### end Alembic commands ###
