"""Add is annotation processed in papers

Revision ID: c8acb557bdd6
Revises: b28693579b91
Create Date: 2023-12-17 08:36:12.375469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8acb557bdd6'
down_revision = 'b28693579b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_annotation_processed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('is_annotation_processed')

    # ### end Alembic commands ###
