"""Add index to cso_uri and label in topics table

Revision ID: d4865d22d392
Revises: c8acb557bdd6
Create Date: 2024-01-10 00:36:14.782773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4865d22d392'
down_revision = 'c8acb557bdd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint('topics_cso_uri_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_topics_cso_uri'), ['cso_uri'], unique=True)
        batch_op.create_index(batch_op.f('ix_topics_label'), ['label'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_label'))
        batch_op.drop_index(batch_op.f('ix_topics_cso_uri'))
        batch_op.create_unique_constraint('topics_cso_uri_key', ['cso_uri'])

    # ### end Alembic commands ###
