"""Change column name

Revision ID: fe3ae439d071
Revises: 59bd6f8e9926
Create Date: 2023-11-24 21:25:53.107887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe3ae439d071'
down_revision = '59bd6f8e9926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('publishedDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publishedDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('published_date')

    # ### end Alembic commands ###
